#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bsp or float (default: float)
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xffd75d74
yabai -m config normal_window_border_color   0xff000000
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config split_ratio                  0.50

# on or off (default: off)
yabai -m config auto_balance on

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set modifier + left-click to focus window (default: none)
yabai -m config focus_follows_mouse autofocus

# focus window under cursor
yabai -m window --focus mouse

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

yabai -m rule --add label=emacs app=Emacs manage=on

setup_space 1 1
setup_space 2 2
setup_space 3 3
setup_space 4 4
setup_space 5 5
setup_space 6 6
setup_space 7 7

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Preview$" manage=on
yabai -m rule --add app="^Sign in - Google Accounts$" manage=off

echo "yabai configuration loaded.."

sketchybar --config "$HOME/.config/sketchybar/sketchybarrc-laptop" &
