#!/usr/bin/env zsh

# Font settings
FONT_FACE="JetBrainsMono Nerd Font"

# Plugin directory and Spotify event
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

# General bar settings
sketchybar --bar \
	   height=34 \
	   color=0x00000000 \
	   margin=3 \
	   sticky=on \
	   topmost=off \
	   padding_top=5 \
	   padding_left=5 \
	   padding_right=5 \
	   notch_width=230 \
	   display=main

# Default item styling
sketchybar --default \
	   background.color=0xff000000 \
	   background.corner_radius=5 \
	   background.padding_right=3 \
	   background.height=20 \
	   icon.font="$FONT_FACE:Bold:15.0" \
	   icon.padding_left=5 \
	   icon.padding_right=5 \
	   label.font="$FONT_FACE:Medium:13.0" \
	   label.color=0xffcad3f5 \
	   label.y_offset=0 \
	   label.padding_left=0 \
	   label.padding_right=5

# Spotify settings
sketchybar --add event spotify_change $SPOTIFY_EVENT \
	   --add item spotify e \
	   --set spotify \
	   icon= \
	   icon.y_offset=1 \
	   icon.font="$FONT_FACE:Bold:15.0" \
	   label.drawing=off \
	   label.padding_left=3 \
	   script="$PLUGIN_DIR/spotify.sh" \
	   --subscribe spotify spotify_change mouse.clicked

# Front app settings
sketchybar --add item front_app left \
	   --set front_app \
	   background.color=0xffa6da95 \
	   background.padding_left=0 \
	   background.padding_right=0 \
	   icon.y_offset=1 \
	   icon.color=0xff24273a \
	   label.drawing=no \
	   script="$PLUGIN_DIR/front_app.sh"

# Separator settings for front app
sketchybar --add item front_app.separator left \
	   --set front_app.separator \
	   background.color=0x00000000 \
	   background.padding_left=-3 \
	   icon= \
	   icon.color=0xffa6da95 \
	   icon.font="$FONT_FACE:Bold:15.0" \
	   icon.padding_left=0 \
	   icon.padding_right=0 \
	   icon.y_offset=1 \
	   label.drawing=no

# Name settings for front app
sketchybar --add item front_app.name left \
	   --set front_app.name \
	   background.color=0x00000000 \
	   background.padding_right=0 \
	   icon.drawing=off \
	   label.font="$FONT_FACE:Bold:12.0" \
	   label.drawing=yes

# Front app bracket for switching
sketchybar --add bracket front_app_bracket \
	   front_app \
	   front_app.separator \
	   front_app.name \
	   --subscribe front_app front_app_switched

# Clock settings
sketchybar --add item clock right \
	   --set clock \
	   icon=󰃰 \
	   icon.color=0xffed8796 \
	   update_freq=10 \
	   script="$PLUGIN_DIR/clock.sh"

# Battery settings
sketchybar --add item battery right \
	   --set battery \
	   update_freq=20 \
	   script="$PLUGIN_DIR/battery.sh"

# Final setup updates and triggers
sketchybar --update
sketchybar --trigger space_change
