# Primary color scheme
[colors.primary]
background = '#000000'
foreground = '#e0def4'

# Bright colors
[colors.bright]
black = '#4f4b66'   
blue = '#8dbfdb'
cyan = '#e1a3a8'
green = '#265d80'
magenta = '#ab87c8'
red = '#e25470'
white = '#bfbcca'
yellow = '#e1a35e'

# Cursor settings
[colors.cursor]
cursor = '#3d385c'
text = '#e0def4'

# Selection colors
[colors.selection]
background = '#403d52'
text = '#e0def4'

# Hint colors
[colors.hints.end]
background = '#191724'
foreground = '#4f4b66'

[colors.hints.start]
background = '#191724'
foreground = '#7c7899'

# Vi mode cursor
[colors.vi_mode_cursor]
cursor = '#524f67'
text = '#e0def4'

# Font settings
[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

# Scrolling and window settings
[scrolling]
history = 10000

[window]
opacity = 1
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

# Clipboard settings
[selection]
save_to_clipboard = true